"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDown, ArrowUp, Check, ChevronDown, ChevronRight, CircleDot, Cloud, Code2, FileCode2, FolderGit2, GitBranch, GitCommitHorizontal, GitFork, GitMerge, History, RefreshCw, Search, Server, ShieldAlert, Terminal, Trash2, X } from "lucide-react";
import { Branch, ChangeFile, Commit, GitSnapshot, MockGitService, initialGitSnapshot } from "./mockGitService";

const service = new MockGitService();
const statusStyles: Record<string, string> = { clean: "bg-emerald-50 text-emerald-700", modified: "bg-amber-50 text-amber-700", ahead: "bg-blue-50 text-blue-700", behind: "bg-violet-50 text-violet-700", conflict: "bg-red-50 text-red-700" };
const diffLines = [
  { type: "context", old: 1, next: 1, text: "import { GitStatus } from \"./types\";" },
  { type: "remove", old: 2, next: "", text: "const status = \"clean\";" },
  { type: "add", old: "", next: 2, text: "const status: GitStatus = \"modified\";" },
  { type: "context", old: 3, next: 3, text: "export default status;" },
];

function Button({ children, onClick, tone = "default", disabled = false, title }: { children: React.ReactNode; onClick?: () => void; tone?: "default" | "primary" | "danger"; disabled?: boolean; title?: string }) {
  const tones = { default: "border-slate-200 bg-white text-slate-700 hover:bg-slate-50", primary: "border-indigo-600 bg-indigo-600 text-white hover:bg-indigo-700", danger: "border-red-200 bg-red-50 text-red-700 hover:bg-red-100" };
  return <button title={title} disabled={disabled} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold transition disabled:cursor-not-allowed disabled:opacity-40 ${tones[tone]}`}>{children}</button>;
}
function Section({ title, icon, badge, children, className = "" }: { title: string; icon: React.ReactNode; badge?: React.ReactNode; children: React.ReactNode; className?: string }) {
  return <section className={`rounded-xl border border-slate-200 bg-white shadow-sm ${className}`}><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div className="flex items-center gap-2 text-sm font-bold text-slate-800">{icon}{title}</div>{badge}</div><div className="p-4">{children}</div></section>;
}
function FileGroup({ title, files, onSelect, selectedId, onToggle, onAction }: { title: string; files: ChangeFile[]; onSelect: (file: ChangeFile) => void; selectedId: string; onToggle: (id: string) => void; onAction: (action: string, id: string) => void }) {
  if (!files.length) return null;
  return <div className="mb-4 last:mb-0"><div className="mb-2 flex items-center justify-between"><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">{title} <span className="ml-1 rounded bg-slate-100 px-1.5 py-0.5 text-slate-500">{files.length}</span></p></div><div className="space-y-1">{files.map((file) => <div key={file.id} className={`group flex items-center gap-2 rounded-lg px-2 py-2 ${selectedId === file.id ? "bg-indigo-50" : "hover:bg-slate-50"}`}><input type="checkbox" checked={file.selected} onChange={() => onToggle(file.id)} className="accent-indigo-600" /><button onClick={() => onSelect(file)} className="min-w-0 flex-1 text-left"><p className="truncate text-xs font-semibold text-slate-700">{file.name}</p><p className="truncate text-[11px] text-slate-400">{file.path}</p></button><span className={`font-mono text-xs font-bold ${file.state === "D" ? "text-red-600" : file.state === "U" ? "text-violet-600" : file.state === "A" ? "text-emerald-600" : "text-amber-600"}`}>{file.state}</span><button onClick={() => onAction(title === "Staged Changes" ? "unstage" : "stage", file.id)} className="hidden rounded p-1 text-slate-400 hover:bg-white hover:text-indigo-600 group-hover:block" title={title === "Staged Changes" ? "Unstage" : "Stage"}>{title === "Staged Changes" ? <ArrowDown size={14} /> : <ArrowUp size={14} />}</button>{title !== "Staged Changes" && <button onClick={() => onAction("discard", file.id)} className="hidden rounded p-1 text-slate-400 hover:bg-red-50 hover:text-red-600 group-hover:block" title="Discard"><Trash2 size={14} /></button>}</div>)}</div></div>;
}

export default function GitControl() {
  const [snapshot, setSnapshot] = useState<GitSnapshot>(initialGitSnapshot); const [branchSearch, setBranchSearch] = useState(""); const [commitMessage, setCommitMessage] = useState(""); const [selectedCommit, setSelectedCommit] = useState<Commit>(); const [toast, setToast] = useState(""); const [confirm, setConfirm] = useState<{ title: string; description: string; action: () => void }>(); const [historyOpen, setHistoryOpen] = useState(false); const [lastRefresh, setLastRefresh] = useState("just now");
  useEffect(() => { void service.status().then(setSnapshot); }, []);
  const filteredBranches = useMemo(() => snapshot.branches.filter((branch) => branch.name.toLowerCase().includes(branchSearch.toLowerCase())), [snapshot.branches, branchSearch]);
  const selectedFile = [...snapshot.staged, ...snapshot.changes, ...snapshot.untracked].find((file) => file.id === snapshot.selectedFileId);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const logAction = (message: string) => notify(`${message} · API chưa được kết nối`);
  const refresh = async () => { setSnapshot(await service.status()); setLastRefresh("just now"); notify("Repository refreshed · mock data"); };
  const update = async (next: Promise<GitSnapshot>, message: string) => { setSnapshot(await next); notify(message); };
  const toggleFile = (id: string) => setSnapshot((current) => ({ ...current, staged: current.staged.map((file) => file.id === id ? { ...file, selected: !file.selected } : file), changes: current.changes.map((file) => file.id === id ? { ...file, selected: !file.selected } : file), untracked: current.untracked.map((file) => file.id === id ? { ...file, selected: !file.selected } : file) }));
  const fileAction = (action: string, id: string) => { if (action === "discard") setConfirm({ title: "Discard changes?", description: "This mock action represents a destructive discard. No real file will be changed.", action: () => { void update(service.discard([id]), "Discard completed"); setConfirm(undefined); } }); else void update(action === "stage" ? service.stage([id]) : service.unstage([id]), `${action === "stage" ? "Stage" : "Unstage"} completed`); };
  const selectedIds = [...snapshot.staged, ...snapshot.changes, ...snapshot.untracked].filter((file) => file.selected).map((file) => file.id);
  const statusLabel = snapshot.status === "modified" ? "Modified" : snapshot.status[0].toUpperCase() + snapshot.status.slice(1);

  return <div className="min-h-screen bg-slate-50 p-1 text-slate-900">
    <header className="rounded-xl bg-slate-950 px-5 py-5 text-white shadow-lg"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2 text-xs text-slate-400"><FolderGit2 size={15} className="text-indigo-400" />Git Control <span className="text-slate-600">/</span> local workspace</div><h1 className="mt-2 text-2xl font-bold tracking-tight">media_tech_ai</h1><p className="mt-1 text-sm text-slate-400">{snapshot.currentBranch} · {snapshot.repositoryPath}</p></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${statusStyles[snapshot.status]}`}><CircleDot size={12} className="mr-1 inline" />{statusLabel}</span><Button onClick={() => void refresh()}><RefreshCw size={14} />Refresh</Button></div></div><div className="mt-5 flex flex-wrap items-center gap-4 border-t border-white/10 pt-4 text-xs text-slate-400"><span className="flex items-center gap-1.5"><ArrowUp size={14} className="text-blue-400" />Ahead {snapshot.ahead}</span><span className="flex items-center gap-1.5"><ArrowDown size={14} className="text-violet-400" />Behind {snapshot.behind}</span><span>Last refreshed: {lastRefresh}</span></div></header>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="space-y-4">
        <Section title="Repository" icon={<Server size={16} className="text-indigo-500" />}><div className="grid gap-3 sm:grid-cols-2"><div><p className="text-[11px] text-slate-400">Repository path</p><p className="mt-1 truncate font-mono text-xs text-slate-700">{snapshot.repositoryPath}</p></div><div><p className="text-[11px] text-slate-400">Remote origin</p><p className="mt-1 truncate font-mono text-xs text-slate-700">{snapshot.remote}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => logAction("Open Repository")}> <FolderGit2 size={14} />Open Repository</Button><Button onClick={() => logAction("Fetch origin")}><Cloud size={14} />Fetch</Button><Button onClick={() => logAction("Pull origin")}><ArrowDown size={14} />Pull</Button><Button onClick={() => logAction("Push origin")}><ArrowUp size={14} />Push</Button><Button onClick={() => logAction("Sync repository")} tone="primary"><RefreshCw size={14} />Sync</Button></div></Section>
        <Section title="Branches" icon={<GitBranch size={16} className="text-indigo-500" />} badge={<Button onClick={() => logAction("Create branch")}>+ Create branch</Button>}><div className="relative mb-3"><Search size={14} className="absolute left-3 top-2.5 text-slate-400" /><input value={branchSearch} onChange={(event) => setBranchSearch(event.target.value)} placeholder="Search branches..." className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-xs outline-none focus:border-indigo-400" /></div><div className="space-y-2">{filteredBranches.map((branch: Branch) => <div key={branch.name} className={`flex items-center justify-between rounded-lg border p-3 ${branch.current ? "border-indigo-200 bg-indigo-50" : "border-slate-100"}`}><div className="flex items-center gap-2"><GitBranch size={15} className={branch.current ? "text-indigo-600" : "text-slate-400"} /><div><p className="text-xs font-semibold text-slate-800">{branch.name} {branch.current && <span className="ml-1 rounded-full bg-indigo-100 px-2 py-0.5 text-[10px] text-indigo-700">current</span>}</p><p className="mt-1 text-[11px] text-slate-400">{branch.remote}</p></div></div><div className="flex gap-1"><Button onClick={() => update(service.checkout(branch.name), `Checkout ${branch.name}`)} disabled={branch.current}>Checkout</Button><Button onClick={() => logAction(`Merge ${branch.name}`)}><GitMerge size={13} /></Button></div></div>)}</div></Section>
        <Section title="Working Tree / Changes" icon={<Code2 size={16} className="text-indigo-500" />} badge={<div className="flex gap-1"><Button onClick={() => selectedIds.length && void update(service.stage(selectedIds), "Selected files staged")} disabled={!selectedIds.length}>Stage selected</Button><Button onClick={() => setConfirm({ title: "Discard all changes?", description: "This is a destructive mock action. No real files will be deleted.", action: () => { void update(service.discard([...snapshot.changes, ...snapshot.untracked].map((file) => file.id)), "All changes discarded"); setConfirm(undefined); } })} tone="danger"><Trash2 size={13} />Discard all</Button></div>}><FileGroup title="Staged Changes" files={snapshot.staged} selectedId={snapshot.selectedFileId} onSelect={(file) => setSnapshot({ ...snapshot, selectedFileId: file.id })} onToggle={toggleFile} onAction={fileAction} /><FileGroup title="Changes" files={snapshot.changes} selectedId={snapshot.selectedFileId} onSelect={(file) => setSnapshot({ ...snapshot, selectedFileId: file.id })} onToggle={toggleFile} onAction={fileAction} /><FileGroup title="Untracked" files={snapshot.untracked} selectedId={snapshot.selectedFileId} onSelect={(file) => setSnapshot({ ...snapshot, selectedFileId: file.id })} onToggle={toggleFile} onAction={fileAction} />{!snapshot.staged.length && !snapshot.changes.length && !snapshot.untracked.length && <p className="py-8 text-center text-sm text-slate-400">Working tree clean</p>}</Section>
      </div>
      <div className="space-y-4">
        <Section title="Diff Viewer" icon={<FileCode2 size={16} className="text-indigo-500" />} badge={<span className="max-w-28 truncate text-[11px] text-slate-400">{selectedFile?.path || "No file selected"}</span>}><div className="overflow-hidden rounded-lg bg-slate-950 font-mono text-[11px] text-slate-300">{selectedFile ? diffLines.map((line, index) => <div key={index} className={`flex ${line.type === "add" ? "bg-emerald-950/60 text-emerald-200" : line.type === "remove" ? "bg-red-950/60 text-red-200" : ""}`}><span className="w-8 shrink-0 select-none border-r border-white/10 px-2 py-1 text-right text-slate-600">{line.old}</span><span className="w-8 shrink-0 select-none border-r border-white/10 px-2 py-1 text-right text-slate-600">{line.next}</span><span className="px-3 py-1">{line.type === "add" ? "+ " : line.type === "remove" ? "- " : "  "}{line.text}</span></div>) : <p className="p-5 text-slate-500">Select a file to view its diff.</p>}</div></Section>
        <Section title="Commit" icon={<GitCommitHorizontal size={16} className="text-indigo-500" />}><textarea value={commitMessage} onChange={(event) => setCommitMessage(event.target.value)} placeholder="Commit message" rows={4} className="w-full resize-none rounded-lg border border-slate-200 p-3 text-xs outline-none focus:border-indigo-400" /><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-slate-500">{snapshot.staged.length} staged file{snapshot.staged.length === 1 ? "" : "s"}</span><Button tone="primary" disabled={!snapshot.staged.length || !commitMessage.trim()} onClick={() => { void update(service.commit(commitMessage.trim()), "Commit created"); setCommitMessage(""); }}>Commit</Button></div></Section>
        <Section title="Remote Status" icon={<GitFork size={16} className="text-indigo-500" />}><div className="rounded-lg border border-slate-100 p-4"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-slate-700">local/{snapshot.currentBranch}</span><span className="rounded-full bg-amber-50 px-2 py-1 font-semibold text-amber-700">Diverged</span><span className="font-semibold text-slate-700">origin/{snapshot.currentBranch}</span></div><div className="my-4 flex items-center gap-2"><div className="h-px flex-1 bg-blue-300" /><span className="text-[10px] text-blue-600">↑ {snapshot.ahead} ahead</span><span className="text-[10px] text-violet-600">↓ {snapshot.behind} behind</span><div className="h-px flex-1 bg-violet-300" /></div><div className="grid grid-cols-3 text-center text-[11px] text-slate-400"><span>Local</span><span>Remote sync</span><span>Origin</span></div></div></Section>
      </div>
    </div>
    <Section title="History" icon={<History size={16} className="text-indigo-500" />} badge={<Button onClick={() => setHistoryOpen(!historyOpen)}>{historyOpen ? "Hide" : "Show all"}<ChevronDown size={14} /></Button>}><div className="space-y-1">{snapshot.history.slice(0, historyOpen ? 8 : 4).map((commit) => <button key={commit.hash} onClick={() => setSelectedCommit(commit)} className={`flex w-full items-center gap-3 rounded-lg border-b border-slate-100 px-2 py-3 text-left last:border-0 hover:bg-slate-50 ${selectedCommit?.hash === commit.hash ? "bg-indigo-50" : ""}`}><span className="font-mono text-xs text-indigo-600">{commit.hash}</span><span className="min-w-0 flex-1 truncate text-xs font-semibold text-slate-700">{commit.message}</span><span className="hidden text-[11px] text-slate-400 sm:block">{commit.author}</span><span className="text-[11px] text-slate-400">{commit.date}</span><ChevronRight size={14} className="text-slate-300" /></button>)}</div>{selectedCommit && <div className="mt-4 rounded-lg bg-slate-50 p-4 text-xs"><div className="flex items-center justify-between"><p className="font-bold text-slate-800">{selectedCommit.message}</p><button onClick={() => setSelectedCommit(undefined)}><X size={14} className="text-slate-400" /></button></div><p className="mt-2 font-mono text-slate-500">{selectedCommit.hash} · parent {selectedCommit.parent} · {selectedCommit.author}</p><p className="mt-3 font-semibold text-slate-600">Changed files</p><ul className="mt-1 list-inside list-disc text-slate-500">{selectedCommit.files.map((file) => <li key={file}>{file}</li>)}</ul></div>}</Section>
    <div className="grid gap-4 lg:grid-cols-[1fr_340px]"><Section title="Git Activity" icon={<Terminal size={16} className="text-indigo-500" />}><div className="space-y-2 font-mono text-[11px] text-slate-500"><p><span className="text-slate-400">18:30</span> Fetch origin</p><p><span className="text-slate-400">18:31</span> Checkout develop</p><p><span className="text-slate-400">18:32</span> Stage src/app.ts</p><p><span className="text-slate-400">18:33</span> Commit &quot;fix UI&quot;</p><p><span className="text-indigo-500">now</span> Mock service ready · no API calls made</p></div></Section><Section title="Advanced / Danger Zone" icon={<ShieldAlert size={16} className="text-red-500" />}><p className="mb-3 text-xs leading-5 text-slate-500">Destructive Git actions are disabled in mock mode and require confirmation.</p><div className="grid grid-cols-2 gap-2"><Button tone="danger" onClick={() => setConfirm({ title: "Reset repository?", description: "Reset actions can discard local work. This mock will not execute a real reset.", action: () => { logAction("Reset requested"); setConfirm(undefined); } })}>Reset</Button><Button tone="danger" onClick={() => setConfirm({ title: "Clean untracked files?", description: "This can remove untracked files. This mock will not delete anything.", action: () => { logAction("Clean requested"); setConfirm(undefined); } })}>Clean</Button><Button tone="danger" onClick={() => setConfirm({ title: "Abort merge?", description: "This mock action does not touch the repository.", action: () => { logAction("Abort merge requested"); setConfirm(undefined); } })}>Abort merge</Button></div></Section></div>
    {toast && <div className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-xs font-semibold text-white shadow-xl"><Check size={15} className="text-emerald-400" />{toast}</div>}
    {confirm && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start gap-3"><div className="rounded-full bg-red-50 p-2 text-red-600"><AlertTriangle size={18} /></div><div><h2 className="font-bold text-slate-900">{confirm.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{confirm.description}</p></div></div><div className="mt-5 flex justify-end gap-2"><Button onClick={() => setConfirm(undefined)}>Cancel</Button><Button tone="danger" onClick={confirm.action}>Confirm mock action</Button></div></div></div>}
  </div>;
}
