"use client";

import {
    useLayoutEffect,
    useRef,
    useState,
} from "react";

/*
 * Layout của MetaPill được căn hoàn toàn bằng HTML/CSS.
 * Hook này chỉ cung cấp các ref mà orders_pill_pack.jsx cần để render icon.
 */
export function useAlignIconCenterToTextCenterFromFrameGaps(
    label = "",
    logLayout = false
) {
    const pillRef = useRef(null);
    const rowRef = useRef(null);
    const textRef = useRef(null);
    const svgRef = useRef(null);
    const graphicRef = useRef(null);
    const boundsRef = useRef(null);
    const measureRef = useRef(null);
    const [isMeasured, setIsMeasured] = useState(false);

    useLayoutEffect(() => {
        const pill = pillRef.current;

        if (!pill) {
            return undefined;
        }

        let isMeasuring = false;
        let frameId = 0;

        const updatePillLayout = () => {
            if (isMeasuring) {
                return;
            }

            isMeasuring = true;
            setIsMeasured(false);

            const contentOffsetY = 0;
            const contentPaddingBottom = 0;
            pill.style.setProperty(
                "--meta-content-offset-y",
                `${contentOffsetY}px`
            );
            pill.style.setProperty(
                "--meta-content-padding-bottom",
                `${contentPaddingBottom}px`
            );

            // Measure the natural rendered pill, not the sizing generated by
            // the previous pass. Then freeze that measured viewport height.
            pill.style.removeProperty("height");
            pill.style.removeProperty("--meta-anchor-height");
            pill.style.removeProperty("--meta-content-height");

            const pillRect =
                pill.getBoundingClientRect();
            const pillHeightCss = pillRect.height;

            if (pillHeightCss <= 0) {
                isMeasuring = false;
                return;
            }

            pill.style.setProperty(
                "--meta-content-shift-y",
                `${pillHeightCss * -0.03}px`
            );

            const anchorHeightChrome =
                pillHeightCss * 0.24;
            const anchorHeight =
                anchorHeightChrome;
            const contentHeight =
                Math.max(
                    0,
                    pillHeightCss -
                        anchorHeight -
                        2
                );

            pill.style.setProperty(
                "--meta-anchor-height",
                `${anchorHeight}px`
            );
            pill.style.setProperty(
                "--meta-content-height",
                `${contentHeight}px`
            );
            pill.style.setProperty(
                "--meta-icon-offset-y",
                "0px"
            );
            pill.style.height = `${pillHeightCss}px`;
            requestAnimationFrame(() => {
                requestAnimationFrame(() => {
                    const content =
                        pill.querySelector(
                            '[data-orders-meta-content-layer="true"]'
                        );
                    const anchor =
                        pill.querySelector(
                            '[data-orders-meta-anchor="true"]'
                        );

                    if (!content || !anchor) {
                        setIsMeasured(true);
                        return;
                    }

                    // Apply the fixed icon adjustment before measuring the
                    // final content position, so the correction includes the
                    // icon's real rendered position.
                    pill.style.setProperty(
                        "--meta-icon-offset-y",
                        `${anchorHeight * 0.12}px`
                    );

                    pill.style.setProperty(
                        "--meta-content-offset-y",
                        "0px"
                    );

                    const contentRow =
                        content.firstElementChild ||
                        content;
                    const contentRect =
                        contentRow.getBoundingClientRect();
                    const text =
                        pill.querySelector(
                            '[data-orders-meta-text="true"]'
                        );
                    const icon = pill.querySelector("svg");
                    const textBottom = text
                        ? text.getBoundingClientRect().bottom
                        : contentRect.bottom;
                    const iconBottom = icon
                        ? icon.getBoundingClientRect().bottom
                        : contentRect.bottom;
                    const anchorRect =
                        anchor.getBoundingClientRect();
                    const correction =
                        anchorRect.top -
                        Math.max(
                            textBottom,
                            iconBottom
                        ) + 4;

                    pill.style.setProperty(
                        "--meta-content-offset-y",
                        `${correction}px`
                    );

                    requestAnimationFrame(() => {
                        requestAnimationFrame(() => {
                            setIsMeasured(true);
                        });
                    });
                });
            });

            if (logLayout) {
                console.table([
                    {
                        Label:
                            label,
                        PillTopViewport:
                            `${pillRect.top.toFixed(4)}px`,
                        PillBottomViewport:
                            `${pillRect.bottom.toFixed(4)}px`,
                    PillHeightViewport:
                        `${pillHeightCss.toFixed(4)}px`,
                    AnchorHeightViewport:
                        `${(
                            anchorHeightChrome
                        ).toFixed(4)}px`,
                    AnchorRatio:
                        "24%",
                    },
                ]);
            }

            isMeasuring = false;
        };

        updatePillLayout();

        const scheduleUpdate = () => {
            cancelAnimationFrame(frameId);
            frameId = requestAnimationFrame(
                updatePillLayout
            );
        };

        window.addEventListener("resize", scheduleUpdate);
        window.visualViewport?.addEventListener(
            "resize",
            scheduleUpdate
        );

        return () => {
            cancelAnimationFrame(frameId);
            window.removeEventListener(
                "resize",
                scheduleUpdate
            );
            window.visualViewport?.removeEventListener(
                "resize",
                scheduleUpdate
            );
        };
    }, [label, logLayout, pillRef]);

    return {
        pillRef,
        rowRef,
        textRef,
        svgRef,
        graphicRef,
        boundsRef,
        measureRef,
        isMeasured,
    };
}
